#Create Aeronautics Toolgun Client Settings
#Thu Jun 25 22:39:45 PST 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectedSublevelProximity=0.5
connectionMode=FREE
deleteRange=10
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=0
offsetX=0
offsetY=0
offsetZ=0
panel=BLUEPRINTS
previewEnabled=true
rangeDeleteEnabled=true
rotationDegrees=240
rotationStep=15
scalePercent=100
selectedFile=native\:the smash burger.excraft
snapMode=LEGACY
translateStep=0.25
weldAdjustStep=0.25
weldSelectionMode=FACE_POINTS
